@startuml
autonumber

actor "Client" as CLN
participant ":ClientLogInUI" as UI
participant ":ClientLogInController" as CTRL
participant ":LogIn" as LOGIN
participant ":User" as USER

activate CLN
CLN -> UI : Log In as Client
activate UI
UI -> CLN : Asks for email and password
deactivate UI
CLN -> UI : Introduces data
activate UI

UI -> CTRL : logIn(email, password)
activate CTRL
CTRL -> LOGIN : logIn(email, password)
activate LOGIN
LOGIN -> USER : getUser(email, password)
activate USER
deactivate USER
deactivate LOGIN
deactivate CTRL
UI --> CLN : LogIn Confirmed
deactivate UI
deactivate CLN
@enduml
@enduml
