@startuml
autonumber
'hide footbox
actor "Admin" as ADM

participant ":UpdatePharmacyUI" as UI
participant ":UpdatePharmacyController" as CTRL
participant ":Platform" as PLAT
participant "UPDPH: UpdatePharmacy" as UPDPH
participant "PHARM: Pharmacy" as PHARM
participant "addr: Address" as ADDR
participant "pc: PostalCode" as PC

activate ADM

ADM -> UI : initiates the Pharmacy creation\n (1 part of the update)
activate UI
UI --> ADM : requests Pharmacy data (name, nif, postalCode,\n idAdmin, coordinateX, coordinateY)
deactivate UI

ADM -> UI : inserts requested data
activate UI
UI -> CTRL : newPharmacy(name, nif, postalCode, idAdmin,\n coordinateX, coordinateY)
activate CTRL
CTRL -> PLAT : updph=getRegisterPharmacy()
activate PLAT
deactivate PLAT
CTRL -> UPDPH : newPharmacy(name, nif, postalCode, idAdmin,\n coordinateX, coordinateY)
activate UPDPH
UPDPH --> PHARM** : create(name, nif, postalCode, idAdmin,\n coordinateX, coordinateY)
activate PHARM
PHARM --> ADDR** : create(postalCode, coordinateX, coordinateY)
activate ADDR
ADDR --> PC** : create(postalCode)
deactivate ADDR
deactivate PHARM
deactivate UPDPH
deactivate CTRL
UI --> ADM : shows data and asks for confirmation
deactivate UI

ADM -> UI : confirms
activate UI
UI -> CTRL : registerPharmacy()
activate CTRL
CTRL -> UPDPH : registerPharmacy(pharm)
activate UPDPH
UPDPH -> UPDPH : validatesPharmacy(pharm)
UI --> ADM : informs the successful operation
deactivate UPDPH
deactivate CTRL
deactivate UI

deactivate ADM

@enduml

