@startuml
autonumber
actor "Client" as CLN

activate CLN
CLN -> ":Platform" : confirms an order and starts automatic payment process
activate ":Platform"
":Platform" --> CLN : begins the automatic payment process and generates an invoice and sends it by email
deactivate ":Platform"

CLN -> CLN : receives invoice by email

deactivate CLN
@enduml
