@startuml
skinparam classAttributeIconSize 0

left to right direction

class Client {
  -String name
  -String email
  -int NIF
  -CreditCard card
  -Address address
}

class Order {
  -String orderID
  -String clientID
  -Map<Product, Integer> cart
}

Client "1" --> "1" Order : has placed >


@enduml


