CREATE OR REPLACE PROCEDURE addInvoice(orderID NUMBER, dateV Timestamp)
AS
    BEGIN
        INSERT INTO INVOICE(ORDERID_ORDER, DATE_INVOICE) VALUES (orderID, dateV);

    end;
/

CREATE OR REPLACE FUNCTION getLatestInvoice
RETURN SYS_REFCURSOR
AS
    invID SYS_REFCURSOR;
    BEGIN
        OPEN invID FOR SELECT MAX(ID_INVOICE) FROM INVOICE;
        RETURN invID;
    end;
/