CREATE OR REPLACE PROCEDURE addStock(phID number)
AS
    BEGIN
        INSERT INTO STOCK(PHARMACYID_PHARMACY) VALUES (phID);
    end;
/

CREATE OR REPLACE FUNCTION getStock(phID number)
RETURN SYS_REFCURSOR
AS
    stockV SYS_REFCURSOR;
BEGIN
    OPEN stockV FOR SELECT * FROM STOCK WHERE PHARMACYID_PHARMACY = phID;
    RETURN stockV;
end;
